download_url: https://galaxy.ansible.com/download/cloud-common-2.1.1.tar.gz
format_version: 1.0.0
name: common
namespace: cloud
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.1.1
version_url: https://galaxy.ansible.com/api/v2/collections/cloud/common/versions/2.1.1/
